### ISSUE TITLE
Error while running CLI starter

### ISSUE THREAD

**Issue by aivannikov** [strapi/strapi-starter-next-corporate#54]
While running the following command `npx create-strapi-starter my-site next-corporate` I get the following error:

Installing strapi/strapi-starter-next-corporate starter
⠸ Installing dependencies:This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cms-strapi@1.0.0
npm ERR! Found: next@11.0.1
npm ERR! node_modules/next
npm ERR!   next@"^11.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^8.1.1-canary.54 || ^9.0.0" from next-seo@4.7.1
npm ERR! node_modules/next-seo
npm ERR!   next-seo@"^4.7.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/alex/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2021-08-08T10_05_53_062Z-debug.log
    at makeError (/home/alex/.npm/_npx/ecd569b0a81a6814/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/alex/.npm/_npx/ecd569b0a81a6814/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installWithLogs (/home/alex/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/build-starter.js:82:3)
    at async buildStarter (/home/alex/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/build-starter.js:151:3)
⠹ Installing dependencies:  ERR! A complete log of this run can be found in: npm ERR!     /home/alex/.npm/_logs/2021-08-08T10_05_53_062Z-debug.log

Please, help how to resolve

**Comment by DevDaveJ** [comment]
Exactly the same bug.

My setup is a custom install of the starter because Im using postgres. backend installs fine, frontend bugs out with the same error as above.

**Comment by Saad-Reapet** [comment]
can you please mention the environment details to reproduce ?
1) OS
2) node version

**Comment by Saad-ISAA** [comment]
can you please mention the environment details to reproduce ?

OS
node version

**Comment by DevDaveJ** [comment]
> 
> 
> can you please mention the environment details to reproduce ?
> 
> OS
> node version

in my case:
Git for Windows v2.29.1
node version 14.15.4
Windows 10 64bit

**Comment by Saad-ISAA** [comment]
I'll reproduce in the same environment and revert back

**Comment by DevDaveJ** [comment]
> 
> 
> I'll reproduce in the same environment and revert back

Ok. Any update on this?

**Comment by DevDaveJ** [comment]
![strapi-starter](https://user-images.githubusercontent.com/68554476/129690052-1567f1b4-b28f-49e3-864b-eadcfef5ec62.jpg)

**Comment by nathan1505** [comment]
I have the exact same bug while running the command. Here is my environment:
Git for Windows v2.33.0
node version 14.17.4
Windows 10 64bit

**Comment by OlympicLarry** [comment]
Try with Node 12.

**Comment by ZodiacWind** [comment]
I have encountered the same issue

**Comment by npoch** [comment]
I just ran npm update and re-ran npm run dev and it started working.

**Comment by Mead42** [comment]
Looks like the next-seo package isn't compatible with NextJS 11. 

Try running:
`npm install --legacy-peer-deps`
